### ISSUE TITLE
Go client error 

### ISSUE THREAD

**Issue by senthilmk** [TileDB-Inc/TileDB-Go#104]
github.com/!tile!d!b-!inc/!tile!d!b-!go@v0.8.4/array.go:6:10: fatal error: 'tiledb/tiledb.h' file not found
#include <tiledb/tiledb.h>

OS: MacOS
Golang version 1.14

**Comment by Shelnutt2** [comment]
@senthilmk for the TileDB-Go API you must first installed TileDB library on your system. For OSX we offer prebuilt packages via homebrew or conda, or you can compile from source. Please see our [prebuild-packages docs](https://docs.tiledb.com/developer/installation/pre-built-packages) for more details on brew or conda installations.

Please let us know if you continue to have problems installing TileDB or getting TileDB-Go to compile afterwards.
