### ISSUE TITLE
'tiledb/tiledb_serialization.h' file not found

### ISSUE THREAD

**Issue by robindarby** [TileDB-Inc/TileDB-Go#130]
OSX.
Installed tileDB via brew:
brew install tiledb-inc/stable/tiledb

Attempting to install go library via:
go get -v github.com/TileDB-Inc/TileDB-Go

Result:
```
$ go get -v github.com/TileDB-Inc/TileDB-Go
github.com/TileDB-Inc/TileDB-Go
# github.com/TileDB-Inc/TileDB-Go
../../go/src/github.com/TileDB-Inc/TileDB-Go/array_schema.go:7:10: fatal error: 'tiledb/tiledb_serialization.h' file not found
#include <tiledb/tiledb_serialization.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by Shelnutt2** [comment]
@robindarby Our homebrew package does not have serialization enabled. I have two PRs up to address this along with updating the version to our latest release from last week. We should have homebrew updated shortly. I will reply to this issue when the package is updated and you should be able to install the go API.

Homebrew PRs:
https://github.com/TileDB-Inc/homebrew-stable/pull/39
https://github.com/TileDB-Inc/homebrew-stable/pull/40

**Comment by Shelnutt2** [comment]
@robindarby The homebrew package has been updated to the latest TileDB version. If you update `brew upgrade tiledb-inc/stable/tiledb` then the go get command should work.

**Comment by robindarby** [comment]
Looks good (YaY) - thank you.
