### ISSUE TITLE
Panic whilst attempting to Seek using VFS module

### ISSUE THREAD

**Issue by sixy6e** [TileDB-Inc/TileDB-Go#261]
Hi, I've just started learning Go and the TileDB-Go API, and I came across an issue when using VFS to read a raw binary file.  I'm testing with TileDB-2.8.0 and TileDB-Go-0.15.0.

The issue occurred after I opened the file and immediately attempted to call seek on the file handler.

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c30a2]

goroutine 1 [running]:
github.com/TileDB-Inc/TileDB-Go.(*VFSfh).Seek(0xc000098000, 0xd4, 0xc00004fc58?)
	/home/user/go/pkg/mod/github.com/!tile!d!b-!inc/!tile!d!b-!go@v0.15.0/vfs.go:595 +0x1a2
```

 I believe it is because the internal variable `size` on the file handler `*VFSfh` isn't set and defaults to `nil` once the file has been opened, as when I modify the Seek function and repeat [this block](https://github.com/TileDB-Inc/TileDB-Go/blob/v0.15.0/vfs.go#L580-L585) before the [offset check](https://github.com/TileDB-Inc/TileDB-Go/blob/v0.15.0/vfs.go#L592), the Seek operation works as expected.

The following is the general gist of what I'm doing:

```Go
    pathname := "<path to some file>"

    config, err := tiledb.NewConfig()
    checkError(err)
    defer config.Free()

    ctx, err := tiledb.NewContext(config)
    checkError(err)
    defer ctx.Free()

    vfs, err := tiledb.NewVFS(ctx, config)
    checkError(err)
    defer vfs.Free()

    stream, err := vfs.Open(pathname, tiledb.TILEDB_VFS_READ)
    checkError(err)
    defer stream.Close()
    defer stream.Free()

    fmt.Println(vfs.FileSize(pathname))
    fmt.Println(stream.IsClosed())

    fmt.Println("about to seek")
    pos, err := stream.Seek(int64(212), 0)
    checkError(err)
```

**Comment by antalakas** [comment]
Hello @sixy6e, thank you for reporting.
We are investigating the issue and will come back soon

**Comment by sixy6e** [comment]
Fantastic, thanks @antalakas.  I look forward to your findings.
