### ISSUE TITLE
C.int and C.int32_t

### ISSUE THREAD

**Issue by mfawzysami** [TileDB-Inc/TileDB-Go#64]
../../src/github.com/TileDB-Inc/TileDB-Go/array.go:269: cannot use &isEmpty (type *C.int) as type *C.int32_t in argument to _Cfunc_tiledb_array_get_non_empty_domain

../../src/github.com/TileDB-Inc/TileDB-Go/array.go:269: cannot use _Cfunc_tiledb_array_get_non_empty_domain(_cgoCheckPointer((*C.struct_tiledb_ctx_t)(a.context.tiledbContext)).(*C.struct_tiledb_ctx_t), _cgoCheckPointer((*C.struct_tiledb_array_t)(a.tiledbArray)).(*C.struct_tiledb_array_t), _cgoCheckPointer0(unsafe.Pointer(&tmpDomain[0]), tmpDomain), &isEmpty) (type C.int32_t) as type C.int in assignment

../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:289: cannot use &isEmpty (type *C.int) as type *C.int32_t in argument to _Cfunc_tiledb_array_get_non_empty_domain
../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:289: cannot use _Cfunc_tiledb_array_get_non_empty_domain(_cgoCheckPointer((*C.struct_tiledb_ctx_t)(a.context.tiledbContext)).(*C.struct_tiledb_ctx_t), _cgoCheckPointer((*C.struct_tiledb_array_t)(a.tiledbArray)).(*C.struct_tiledb_array_t), _cgoCheckPointer0(unsafe.Pointer(&tmpDomain[0]), tmpDomain), &isEmpty) (type C.int32_t) as type C.int in assignment
../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:309: cannot use &isEmpty (type *C.int) as type *C.int32_t in argument to _Cfunc_tiledb_array_get_non_empty_domain
../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:309: cannot use _Cfunc_tiledb_array_get_non_empty_domain(_cgoCheckPointer((*C.struct_tiledb_ctx_t)(a.context.tiledbContext)).(*C.struct_tiledb_ctx_t), _cgoCheckPointer((*C.struct_tiledb_array_t)(a.tiledbArray)).(*C.struct_tiledb_array_t), _cgoCheckPointer0(unsafe.Pointer(&tmpDomain[0]), tmpDomain), &isEmpty) (type C.int32_t) as type C.int in assignment
../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:329: cannot use &isEmpty (type *C.int) as type *C.int32_t in argument to _Cfunc_tiledb_array_get_non_empty_domain
../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:329: cannot use _Cfunc_tiledb_array_get_non_empty_domain(_cgoCheckPointer((*C.struct_tiledb_ctx_t)(a.context.tiledbContext)).(*C.struct_tiledb_ctx_t), _cgoCheckPointer((*C.struct_tiledb_array_t)(a.tiledbArray)).(*C.struct_tiledb_array_t), _cgoCheckPointer0(unsafe.Pointer(&tmpDomain[0]), tmpDomain), &isEmpty) (type C.int32_t) as type C.int in assignment
../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:349: cannot use &isEmpty (type *C.int) as type *C.int32_t in argument to _Cfunc_tiledb_array_get_non_empty_domain
../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:349: cannot use _Cfunc_tiledb_array_get_non_empty_domain(_cgoCheckPointer((*C.struct_tiledb_ctx_t)(a.context.tiledbContext)).(*C.struct_tiledb_ctx_t), _cgoCheckPointer((*C.struct_tiledb_array_t)(a.tiledbArray)).(*C.struct_tiledb_array_t), _cgoCheckPointer0(unsafe.Pointer(&tmpDomain[0]), tmpDomain), &isEmpty) (type C.int32_t) as type C.int in assignment
../../hivedblibs/src/github.com/TileDB-Inc/TileDB-Go/array.go:349: too many errors

**Comment by Shelnutt2** [comment]
@mfawzysami Thank you for reporting this. We should be using the specific C int types for this, and all other functions.

What cpu architecture (x86_64?) OS, go version and c compiler are you using? I'd like to see if I can setup a similar environment on travis to catch these type mismatches in the future. We had not seen these issues but I suspect its due to C.int being treated as C.int32_t on the current travis environment as well as on our own development environments.

**Comment by mfawzysami** [comment]
@Shelnutt2  I have fixed this already in my local version of TileDB-Go, I fixed this by converting all C.int to C.int32_t and all C.uint to C.uint32_t specially those of `ret`

**Comment by mfawzysami** [comment]
@Shelnutt2 Also, Please don't refer C Constants defined using #define in golang because they are unsupported by Cgo, instead use the exported functions directly

**Comment by mfawzysami** [comment]
@Shelnutt2 I am using x64 Ubuntu 16.04 GCC gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
