### ISSUE TITLE
Adding new Data

### ISSUE THREAD

**Issue by mfawzysami** [TileDB-Inc/TileDB-Go#66]
@Shelnutt2 @antalakas How can i append data to a tiledb using TileDB-Go , assume that i have 4 x 4 dense array matrix that was created in tiledb on disk , how can append a new 1 x 4 dense array into this tiledb database.

I am sorry, this is not an issue, but i created an issue because i don't know where should i write these questions.

**Comment by Shelnutt2** [comment]
@mfawzysami I will assume you are using the [quickstart dense](https://github.com/TileDB-Inc/TileDB-Go/blob/master/examples/quickstart_dense_test.go) example, where dense array is created as a 4x4 and had all 16 cell written too. In this case once all values of the dense array written, it is not possible to append additional value. It is possible to update cells with new attribute values, but if you fill a 4x4 array you can not append a new 1x4 array, making it a 5x4 arrays.

Let me explain why and how to achieve what you are looking to do. In the quickstart dense example the two dimensions, `rows` and `cols` are created with domains of `[]int32{1, 4}`. For every dimension you can define the range of all possible values, which is called the `domain of the dimension`. If you wanted to have a 5x4 array, you could create the row dimension as `[]int32{1, 5}`. Modifying the quickstart example we'd get:

```
// The array will be 5x4 with dimensions "rows" and "cols"
domain, err := tiledb.NewDomain(ctx)
checkError(err)
rowDim, err := tiledb.NewDimension(ctx, "rows", []int32{1, 5}, int32(5))
checkError(err)
colDim, err := tiledb.NewDimension(ctx, "cols", []int32{1, 4}, int32(4))
checkError(err)
err = domain.AddDimensions(rowDim, colDim)
checkError(err)
```

Now it would be possible write additional records to the dense array. In general when creating the dimensions it is important to consider the range of possible coordinates you will want to store in the array and make sure to set the dimension's domain large enough. Currently this can not be altered once the array is created.

For more details on multiple writes, see the [multiple write tutorial](https://docs.tiledb.io/en/stable/tutorials/writing-dense.html#multiple-writes-updates) which includes some diagrams explaining the cells that are written at each stage. The tutorial is for c++/python but the example is ported to go [here](https://github.com/TileDB-Inc/TileDB-Go/blob/master/examples/writing_dense_multiple_test.go).

I will also point out, that the next step you might take if performing multiple writes, is you can also do [sparse writes](https://docs.tiledb.io/en/stable/tutorials/writing-dense.html#writing-sparse-cells) to dense arrays. This allows you to write specific cells, which can be useful for updating or when you are appending new data to the array that you want set at specific coordinates.


No worries about posting this here, for future questions we do have a forum at https://forum.tiledb.io

**Comment by mfawzysami** [comment]
@Shelnutt2  I have one more simple question, i need to create a matrix in tiledb that can hold 2 samples and the columns are the variants in the human genome, which is 3.2 Billions , i want to create a matrix with 2 samples x 3.2 Billions Columns , where positions are the offsets and the variants are the variants.

i had this in my go program:
====================

Row Dimensions : 1 x 2
Column Ranges : 1 x 3095693983
Tile Size : 10 * 1024 and sometimes , i choose 1000

Now i am receiving this error,

[2019-04-02 20:28:50.276] [tiledb] [Process: 18691] [Thread: 18691] [error] [TileDB::Dimension] Error: Tile extent check failed; Tile extent exceeds dimension domain range

[2019-04-02 20:28:50.276] [tiledb] [Process: 18691] [Thread: 18691] [error] [TileDB::Dimension] Error: Domain check failed; Upper domain bound should not be smaller than the lower one

Could you please help me with this.

**Comment by mfawzysami** [comment]
@Shelnutt2 @antalakas  Sorry guys , i was passing int32 and trying to create 3 billions which actually exceed the maximum int32 , i converted into int64 fixed the problem.

**Comment by stavrospapadopoulos** [comment]
@mfawzysami, regarding the first error, the tile extent per dimension cannot exceed your dimension domain. For your row domain [1,2], your tile extent can be between 1 and 2. Similarly, for your column domain [1, 3095693983], it must be between 1 and 3095693983.

Regarding the second error, please note that 3,095,693,983 exceeds the max `int32` value and you are experiencing an overflow. So you will need to define your dimensions type to be either `uint32` or `int64`.

**Comment by stavrospapadopoulos** [comment]
Sorry, I just noticed that you had figured out the overflow issue :).
